# ============================================
# VPC & Network Outputs
# ============================================
output "network_name" {
  description = "Name of the VPC network"
  value       = google_compute_network.spark_network.name
}

output "subnet_cidr" {
  description = "CIDR range of the subnet"
  value       = google_compute_subnetwork.spark_subnet.ip_cidr_range
}

# ============================================
# Master Node Outputs
# ============================================
output "master_name" {
  description = "Name of the master VM"
  value       = google_compute_instance.spark_master.name
}

output "master_external_ip" {
  description = "External IP of master VM (for SSH)"
  value       = google_compute_instance.spark_master.network_interface[0].access_config[0].nat_ip
}

output "master_internal_ip" {
  description = "Internal IP of the Master node"
  value       = google_compute_instance.spark_master.network_interface[0].network_ip
}

output "spark_master_ui" {
  description = "URL to access Spark Master Web UI"
  value       = "http://${google_compute_instance.spark_master.network_interface[0].access_config[0].nat_ip}:8080"
}

# ============================================
# Worker Nodes Outputs (Using Splat for Dynamic Count)
# ============================================
output "worker_names" {
  description = "Names of worker nodes"
  value       = google_compute_instance.spark_worker[*].name
}

output "worker_external_ips" {
  description = "External IPs of workers"
  value       = google_compute_instance.spark_worker[*].network_interface[0].access_config[0].nat_ip
}

# ============================================
# Edge Node Outputs
# ============================================
output "edge_name" {
  description = "Name of the edge node"
  value       = google_compute_instance.spark_edge.name
}

output "edge_external_ip" {
  description = "External IP of edge node"
  value       = google_compute_instance.spark_edge.network_interface[0].access_config[0].nat_ip
}

# ============================================
# Storage Node Outputs
# ============================================
output "storage_internal_ip" {
  description = "Internal IP of the Storage node"
  value       = google_compute_instance.spark_storage.network_interface[0].network_ip
}

# ============================================
# Helper Commands
# ============================================
output "ssh_command_edge" {
  description = "Command to SSH into the Edge node for job submission"
  value       = "gcloud compute ssh ${google_compute_instance.spark_edge.name} --zone=${var.zone}"
}

# ============================================
# Ansible Inventory Generation
# ============================================

resource "local_file" "ansible_inventory" {
  filename = "../ansible/inventory/hosts.ini"

  content = <<-EOT
# Auto-generated by Terraform
# Do not edit manually

[all:vars]
ansible_user=${var.ansible_user}
ansible_ssh_private_key_file=~/.ssh/google_compute_engine
ansible_python_interpreter=/usr/bin/python3
# Jump through the Edge Node
ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/google_compute_engine -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q ${var.ansible_user}@${google_compute_instance.spark_edge.network_interface[0].access_config[0].nat_ip}" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[master]
${google_compute_instance.spark_master.name} ansible_host=${google_compute_instance.spark_master.network_interface[0].network_ip}

[workers]
%{ for i in range(length(google_compute_instance.spark_worker)) ~}
${google_compute_instance.spark_worker[i].name} ansible_host=${google_compute_instance.spark_worker[i].network_interface[0].network_ip}
%{ endfor ~}

[edge]
${google_compute_instance.spark_edge.name} ansible_host=${google_compute_instance.spark_edge.network_interface[0].access_config[0].nat_ip} ansible_ssh_common_args=''

[storage]
${google_compute_instance.spark_storage.name} ansible_host=${google_compute_instance.spark_storage.network_interface[0].network_ip}

[cluster:children]
master
workers
edge
storage
EOT
}