[all:vars]
ansible_user=mpsi_mekkaoui_ossama_moussa_gmai
ansible_ssh_private_key_file=~/.ssh/google_compute_engine
ansible_python_interpreter=/usr/bin/python3

[master]
spark-master ansible_host=34.163.124.82

[workers]
spark-worker-1 ansible_host=34.163.224.74
spark-worker-2 ansible_host=34.155.179.91

[cluster:children]
master
workers